apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: guestbook-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`test.glooper.com`)
      priority: 10
      services:
        - name: guestbook-ui
          port: 80
